# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160617_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
